### ISSUE TITLE
Flink compile failed with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by pensz** [davidB/scala-maven-plugin#484]
mvn: 3.2.5
java:  oracle 1.8.0_11 1.8.0_251 1.8.0_291 
code: [flink-release-1.12.2](https://github.com/apache/flink/tree/release-1.12.2)
scala-maven-plugin: 3.2.2
command: 
`cd flink-runtime ; mvn  clean package  -DskipTests`

What I have tried:

 java:  1.8.0_291 
command:  `cd flink-runtime; mvn  clean package -Dscala-2.12 -DskipTests`
compile with scala-2.12 works fine.

FAILURE LOG:

```
[INFO] /data/flink-release-1.12.2/flink-runtime/src/main/java:-1: info: compiling
[INFO] /data/flink-release-1.12.2/flink-runtime/src/main/scala:-1: info: compiling
[INFO] Compiling 1958 source files to /data/flink-release-1.12.2/flink-runtime/target/classes at 1622534247234
[DEBUG] use java command with args in file forced : false
[DEBUG] plugin jar to add :/home/work/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.2.2/scala-maven-plugin-3.2.2.jar
[DEBUG] cmd:  /data/jdk1.8.0_11/jre/bin/java -classpath /home/work/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar:/home/work/.m2/repository/org/scala-lang/scala-compiler/2.11.12/scala-compiler-2.11.12.jar:/home/work/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.2.2/scala-maven-plugin-3.2.2.jar -Xms128m -Xmx512m -Xss2m scala_maven_executions.MainWithArgsInFile scala.tools.nsc.Main /tmp/scala-maven-2566643424193071515.args
[ERROR] java.lang.NoClassDefFoundError: scala/reflect/internal/Trees
[INFO] 	at java.lang.ClassLoader.defineClass1(Native Method)
[INFO] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[INFO] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[INFO] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[INFO] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	at java.lang.ClassLoader.defineClass1(Native Method)
[INFO] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[INFO] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[INFO] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[INFO] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	at java.lang.Class.getDeclaredMethods0(Native Method)
[INFO] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
[INFO] 	at java.lang.Class.getMethod0(Class.java:2937)
[INFO] 	at java.lang.Class.getMethod(Class.java:1771)
[INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:155)
[INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] Caused by: java.lang.ClassNotFoundException: scala.reflect.internal.Trees
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	... 30 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.874 s
[INFO] Finished at: 2021-06-01T15:57:27+08:00
[INFO] Final Memory: 45M/714M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project flink-runtime_2.11: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project flink-runtime_2.11: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:490)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at scala_maven_executions.JavaMainCallerByFork.run(JavaMainCallerByFork.java:100)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:161)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
	... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by davidB** [comment]
It's a old version of the plugin (2015 from https://search.maven.org/artifact/net.alchim31.maven/scala-maven-plugin). I read in the flink's README there is issue with maven 3.3.x, but maybe some update could retry.

About your issue, it's seems that scala-reflect is not included as part of the classpath. I don't understand why you have the issue scala-2.11.12 but not with 2.12 (can you run it and share the line with `cmd: ...` to compare. Anyway it could be a bug of this old version of the plugin, we changed the way to build the classpath several times since (in some version with force scala-reflect in the classpath of the compiler). So try with a newer version of the plugin or fork the plugin (sorry).

**Comment by pensz** [comment]
Thanks for your reply.
With a new version scala-maven-plugin(4.3.0), it works fine too. I just wanna know what cause the problem.

When I use Scala 2.12 the cmd is :
```
[DEBUG] cmd:  /data/jdk1.8.0_291/jre/bin/java -classpath /home/work/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar:/home/work/.m2/repository/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar:/home/work/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar:/home/work/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar:/home/work/.m2/repository/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar:/home/work/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.2.2/scala-maven-plugin-3.2.2.jar -Xms128m -Xmx512m -Xss2m scala_maven_executions.MainWithArgsInFile scala.tools.nsc.Main /tmp/scala-maven-2448136156921473248.args
```

BTW: `flink-runtime` dependeds `scala-reflect` in test scope. Does it affect ?

```
[INFO] +- org.scalatest:scalatest_2.11:jar:3.0.0:test
[INFO] |  +- org.scalactic:scalactic_2.11:jar:3.0.0:test
[INFO] |  +- org.scala-lang:scala-reflect:jar:2.11.12:test
[INFO] |  +- org.scala-lang.modules:scala-xml_2.11:jar:1.0.5:test
[INFO] |  \- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.1.1:compile
```

**Comment by davidB** [comment]
I guess the cause was an issue in the build of classpath for the compiler, missing scala-reflect (but present for 2.12). Recently for 4.5.x I removed the hard-coded injection of scala-reflect,... I guess it was a workaround we introduced for some issue like that (build of the classpath) or old crappy declaration of the dependency of scala-compiler (not always good since scala 2.7 :-D)

**Comment by davidB** [comment]
Thanks for your feedback, and glade there is a solution with a more recent version.
