### ISSUE TITLE
scala:doc in 2.14 broken for Java + Scala (works with 2.13.1)

### ISSUE THREAD

**Issue by awhitford** [davidB/scala-maven-plugin#33]
I just upgraded from 2.13.1 to 2.14 and my scala:doc is broken.  Output looks something like this:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building My Application
[INFO]    task-segment: [scala:doc]
[INFO] ------------------------------------------------------------------------
[INFO] Preparing scala:doc
[INFO] [jaxws:wsimport {execution: wsdl-client}]
[INFO] [scala:doc {execution: default-cli}]
[INFO] Checking for multiple versions of scala
[INFO] Checking for multiple versions of scala
C:\workspaces\my-app\src\main\scala\com\acme\app\snippet\FILE.scala:17: error: value file is not a     member of package com.acme
import com.acme.file.{Wrapper, WrapperService}
                        ^
Jul 4, 2010 11:37:40 AM org.scala_tools.vscaladoc.HtmlRenderer render
INFO: write page for overview
Jul 4, 2010 11:37:40 AM org.scala_tools.vscaladoc.HtmlRenderer render
INFO: write page for all-classes (list)
Jul 4, 2010 11:37:41 AM org.scala_tools.vscaladoc.HtmlRenderer render
INFO: write index.html
Jul 4, 2010 11:37:41 AM org.scala_tools.vscaladoc.HtmlRenderer render
INFO: write doc for  each classes
one error found
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] wrap: org.apache.maven.reporting.MavenReportException: wrap: Process exited with an error: 1(Exit value: 1)

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51 seconds
[INFO] Finished at: Sun Jul 04 11:37:45 PDT 2010
[INFO] Final Memory: 34M/60M
[INFO] ------------------------------------------------------------------------
```

A unique thing about this project is that it leverages the jaxws-maven-plugin to generate java stubs for a wsdl.  It looks like that java code is half integrated into the scaladoc run.  I believe that with 2.13.1, the java code ends up in Javadoc, while the scala code ends up in Scaladoc.
