### ISSUE TITLE
The goal doc-jar leads to duplicate actions during build

### ISSUE THREAD

**Issue by tashoyan** [davidB/scala-maven-plugin#397]
As [documentation](https://davidb.github.io/scala-maven-plugin/doc-jar-mojo.html) says, the goal doc-jar _invokes the execution of the lifecycle phase generate-resources prior to executing itself_.

In our case, we generate some Scala classes from Avro schemas using [avrohugger-maven-plugin](https://github.com/makubi/avrohugger-maven-plugin). The classes are generated on the `generate-resources` phase. Hence, we generate this code twice during a build.

In addition, we auto-format the Scala code (human-written, not auto-generated) with help of Scalariform. This occurs on the `process-sources` phase. So we format the sources twice.

Is it necessary to re-run the `generate-resources` phase? In fact, this leads to duplicate work and longer build time.

Environment:
Maven 3.6.3
Oracle JDK 8
scala-maven-plugin 4.3.1

**Comment by slandelle** [comment]
@davidB Do you remember why this mojo needs to execute `generate-resources` phase?

**Comment by davidB** [comment]
Maybe caused by https://github.com/davidB/scala-maven-plugin/commit/75a058a249e758d8dabc89c94eba8aa3adf675fd
>Beginning with d9f45d0, the doc-jar goal (ScalaDocJarMojo) was not passing a classpath to scaladoc. When running on Java 8, scaladoc reported errors wherever any symbol from a dependency is mentioned (e.g. “object log4s is not a member of package org”, even though log4s is supposed to be on the classpath). When running on Java 10, scaladoc suffered an immediate fatal error instead (“object scala in compiler mirror not found”).
>
>The problem was that ScalaDocJarMojo did not declare that it `requiresDependencyResolution`. In the legacy Javadoc-style annotations for Maven plugins, `@requiresDependencyResolution` is a separate, inherited annotation, so ScalaDocJarMojo inherited it from ScalaDocMojo. With the new annotations, however, `requiresDependencyResolution` is instead a field of the `@Mojo` annotation, which is *not* inherited.

**Comment by slandelle** [comment]
@davidB The funny thing is integration tests are still all green if I remove `@Execute(phase = LifecyclePhase.GENERATE_RESOURCES)` from ScalaDocMojo.

**Comment by slandelle** [comment]
`maven-javadoc-plugin` invokes `generate-sources` phase: http://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html

I can guess this might be to make sure generated code will be documented too.
But why would scala-maven-plugin do something else and invoke `generate-resources` instead?

**Comment by slandelle** [comment]
It's a mistake introduced in https://github.com/davidB/scala-maven-plugin/commit/d9f45d0dae6955b459367b11f97305d2ec2bad75#diff-9080ad9575fe47ad4aeb9defeaad6406R28 :)

Fixing.

**Comment by slandelle** [comment]
@tashoyan Could you please install plugin from sources and confirm this fixes your issue?

**Comment by tashoyan** [comment]
@slandelle This does not fix unfortunately. Now the goal `doc-jar` invokes the `generate-sources` phase. However, the code auto-generation also runs on this phase - still runs twice.

Moreover, all prior lifecycle phases (`validate`, `initialize`) also get re-executed. Not a harm by itself, but it's a bit tricky to troubleshoot failing builds.

I am curious - why it is needed to re-execute previous phases? Is it because the goal `doc-jar` needs Scala sources added by the goal `add-source`, and the latter is bound to the `generate-sources` phase? However, typically we generate Java/Scala docs on a CI system during full build:

- fresh git clone
- mvn deploy

In this scenario, all lifecycle phases are executed in proper order, so no need to re-execute some phase from the past.

**Comment by slandelle** [comment]
> I am curious - why it is needed to re-execute previous phases?

I don't know. Maybe so that code generation also triggers when directly invoking mojo goal instead of triggering from lifecycle.
This would be a question for `maven-javadoc-plugin`. I think we should stick to being aligned with them.

**Comment by slandelle** [comment]
@tashoyan I recommend you reach out on [maven mailing lists](https://maven.apache.org/mailing-lists.html) so you can figure out why `maven-javadoc-plugin` forcefully invokes `generate-sources` phase.
